Feature/update readme
eProsima/Micro-XRCE-DDS pull request #72
Opened 2021-03-08 15:29 UTC by FranFin

2021-03-08 16:50 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Linux&build=174)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/174/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Windows&build=193)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/193/)

2021-03-09 06:17 UTC, pablogs9 approved these changes

2021-03-09 06:55 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Linux&build=175)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/175/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Windows&build=194)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/194/)

2021-03-10 11:03 UTC, pablogs9 commented
LGTM, warning is unrelated, if you are OK merge @jamoralp

2021-03-15 08:43 UTC, jamoralp requested changes

2021-03-15 08:43 UTC, jamoralp commented on README.md
> +- *Micro XRCE-DDS Client*
```suggestion
- *Micro XRCE-DDS Agent*
```

2021-03-15 08:43 UTC, jamoralp commented on README.md
> +- *Micro XRCE-DDS Gen*
I personally would expect this list ot be clickable. Therefore, write something as:
* [Micro XRCE-DDS Client](https://github.com/eProsima/Micro-XRCE-DDS-Client)

2021-03-15 10:07 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Linux&build=176)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/176/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Windows&build=195)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/195/)

2021-03-18 09:12 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Linux&build=177)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/177/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Windows&build=196)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/196/)

2021-03-18 12:49 UTC, richiprosima commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Linux&build=178)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Linux/178/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Micro-XRCE-DDS%20Manual%20Windows&build=197)](http://jenkins.eprosima.com:8080/job/Micro-XRCE-DDS%20Manual%20Windows/197/)

2021-03-18 13:12 UTC, pablogs9 approved these changes

2021-03-18 13:13 UTC, pablogs9 commented
If @jamoralp is ok with this we can merge.

2021-03-22 08:04 UTC, jamoralp approved these changes

2021-03-22 08:04 UTC, merged